### ISSUE TITLE
the model link you shared has expired！

### ISSUE THREAD

**Issue by goodtogood** [chenxinpeng/SSD_scene-text-detection#1]
@chenxinpeng Hi, 
the model link you shared has expired！
would you like to update it？
thx!

**Comment by chenxinpeng** [comment]
Thank you for notice me to update the link, the link has been updated.

在2016-11-19 12:09:09，Xinpeng.Chen2015202130029@whu.edu.cn写道：

@chenxinpeng Hi,
the model link you shared has expired！
would you like to update it？
thx!

**Comment by goodtogood** [comment]
the link works !
thx!
