### ISSUE TITLE
Re-upload caffemodel

### ISSUE THREAD

**Issue by prinsherbert** [chenxinpeng/SSD_scene-text-detection#4]
The trained caffemodel on weiyun has expired, could you upload it somewhere else?

You could create a release at github and add the model as a binary.

Thank you in advance!

**Comment by mojovski** [comment]
same here. The model is lost... :(

**Comment by prinsherbert** [comment]
@chenxinpeng I noticed you already fixed the link once, maybe a permanent solution would be to use a release with an attached binary here on Github.

If you could upload your trained model, that would help me a lot!

Thank you in advance!

**Comment by mojovski** [comment]
Link still not working for me. This is what I get.
20002)外链已过期,请联系分享者重新分享

**Comment by prinsherbert** [comment]
@mojovski I did not fix the link, I can't as I don't have the model.

**Comment by mojovski** [comment]
Oh, thats a pitty. I hope the author will find some time to do so.

**Comment by chenxinpeng** [comment]
@mojovski I am very sorry, the link has been fixed.

**Comment by prinsherbert** [comment]
@chenxinpeng Wouldn't you think the link on weiyun, even if it is fixed now, will expire again? Isn't a sustainable solution like hosting the file as a github-release worth a shot?

**Comment by prinsherbert** [comment]
It's in Dropbox and Google Drive as well, didn't notice that :) Thanks!
